### PR TITLE
change config.json to config.json.template

### PR DESCRIPTION
**Pull request by VasilisPitsiavas**
Changed the configuration local file to config.json for legacy reasons.

### CODE REVIEW

**Comment by pkakelas** [comment]
Maybe you should change that in the codebase, too.

**Comment by VasilisPitsiavas** [comment]
It seems that is already changed.  Maybe we just found out a bug :)

**Comment by pkakelas** [comment]
Ah, you're right! I'm merging you.

**Comment by VasilisPitsiavas** [comment]
Thank you!

**Pull request merged**
